/*
 * This source file was generated by the Gradle 'init' task
 */
package java_mappedbytebuffer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // テスト未実装
}
